name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  docker build -f src/main/docker/Dockerfile.multistage -t test:dev .
    - name: Check Image
      run: docker images
